"""Add background job tracking to ExperimentRun

Revision ID: a8f351fad4d5
Revises: 2ad270ded784
Create Date: 2026-09-19 19:36:33.261689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f351fad4d5'
down_revision: Union[str, Sequence[str], None] = '2ad270ded784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_runs', sa.Column('status', sa.String(length=50), nullable=False, server_default='queued'))
    op.add_column('experiment_runs', sa.Column('progress_samples', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('experiment_runs', sa.Column('total_samples', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('experiment_runs', sa.Column('current_stage', sa.String(length=255), nullable=True))
    op.add_column('experiment_runs', sa.Column('elapsed_time', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_runs', 'elapsed_time')
    op.drop_column('experiment_runs', 'current_stage')
    op.drop_column('experiment_runs', 'total_samples')
    op.drop_column('experiment_runs', 'progress_samples')
    op.drop_column('experiment_runs', 'status')
    # ### end Alembic commands ###
